export const students = [
  {
    id: 14241,
    lastname: "Doe",
    name: "John",
    specialty: "Computer Science",
    group: "2/21",
    module: "M1",
    register: "puntual",
  },
  {
    id: 14242,
    lastname: "Doe",
    name: "Jane",
    specialty: "Computer Science",
    group: "2/21",
    module: "M2",
    register: "puntual",
  },
  {
    id: 14243,
    lastname: "Perez",
    name: "Josue",
    specialty: "Computer Science",
    group: "2/22",
    module: "M2",
    register: "pendiente",
  },
  {
    id: 89393,
    lastname: "Martinez",
    name: "Raul",
    specialty: "Enfermeria",
    group: "2/22",
    module: "M2",
    register: "pendiente",
  },
  {
    id: 33393,
    lastname: "Martinez",
    name: "Maria",
    specialty: "Farmacia",
    group: "2/22",
    module: "M2",
    register: "puntual",
  },
  {
    id: 33393,
    lastname: "Casas",
    name: "Paula Andrea",
    specialty: "Enfermeria",
    group: "2/22",
    module: "M2",
    register: "puntual",
  },
];

export const employees = [
  {
    id: 1,
    lastname: "Doe",
    name: "Martin",
    dni: "12345678",
    email: "martin@gmail.com",
    password: "123",
  },
  {
    id: 2,
    lastname: "Martinez",
    name: "Jose",
    dni: "12345679",
    email: "jose@gmail.com",
    password: "123",
  },
];
